### ISSUE TITLE
Create project structure

### ISSUE THREAD

**Issue by hohwille** [devonfw-sample/archunit#2]
This repository is still empty and needs to be initialized with the initial structure. Templates can be copied from other repos like [devon4j-sonar-plugin](https://github.com/devonfw/sonar-devon4j-plugin).

Acceptance-criteria:
The following files are properly present:
* [x] .gitignore
* [x] pom.xml (needs to be adopted to new GAV, no parent, dependency for archUnit, etc.)
* [x] .github/workflows/build.yml
* [x] .github/workflows/build-pr.yml
* [x] README.adoc (already present but needs to be extended with CI badge and additional doc)

**Comment by Bene90** [comment]
[16.1]Jörg will do a minimal job. Afterwards the task will be assigned to one team member.

**Comment by hohwille** [comment]
I will close this issue that is IMHO already completed.
