### ISSUE TITLE
Create PackageStructure to centralize regex and logic on the package conventions

### ISSUE THREAD

**Issue by vlad961** [devonfw-sample/archunit#33]
Create an `ArchitecturePackage` type based on [sonar-devon4j-plugin's: `DevonPackageImpl`](https://github.com/devonfw/sonar-devon4j-plugin/blob/master/plugin/src/main/java/com/devonfw/ide/sonarqube/common/api/config/DevonPackageImpl.java)

Three methods to create:

- [X] given a JavaClass as input
- [X] given a Package name as input
- [X] given a fully classified class name

Return a `DevonPackage` on which methods like:

- get Component
- get Layer
- get scope
- etc.

can be called to simplify task  [#19](https://github.com/devonfw-sample/archunit/issues/19).

**Comment by hohwille** [comment]
Had been done with PR #34. Hence closing.
